#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
#
# Set this variable according to your
# Visual Studio installation
#
msvs="C:/Program Files/Microsoft Visual Studio/2022/Professional"

script="`basename $0`"
d="`dirname $0`"
srcdir="`cd \"$d\" && pwd`"

xbexit()
{
    e=$1; shift;
    echo "$@" 1>&2
    exit $e
}

test "x$1" = "x" && xbexit 1 "Missing output file"
xout="$1"
xcmd="`cygpath -u $COMSPEC 2>/dev/null`"
xtmp="`cygpath -m /tmp`"
base=vcvars$$

cat > /tmp/$base.bat <<EOH
@echo off
@cd "$msvs"
@call ./VC/Auxiliary/Build/vcvars64.bat >NUL
set >$xtmp/$base.txt
EOH

(
  PATH=$ORIGINAL_PATH
  $xcmd /c $xtmp/$base.bat
)

input="/tmp/$base.txt"
dos2unix -q $input 2>/dev/null || true
echo "# Generated by: $srcdir/$script" > $xout
echo "#" >> $xout
echo "# ComSpec     : $xcmd" >> $xout
echo "# VisualStudio: $msvs" >> $xout
echo "#" >> $xout

while IFS= read -r i
do
	n="`echo \"$i\" | sed -e 's/=.*//'`"
	u="`echo \"$n\" | tr '[:lower:]' '[:upper:]'`"
	v="`echo \"$i\" | sed -e 's/.*=//' -e 's/\\\\/\\//g'`"
	case "$u" in
		DEVENV* | EXTENSION*)
			echo "export $n=\"$v\"" >> $xout
		;;
		FRAMEWORK* | VC* | VS* | VISUAL*)
			echo "export $n=\"$v\"" >> $xout
		;;
		PATH)
			echo "export CYGWRUN_PATH=\"$v\"" >> $xout
		;;
		INCLUDE | LIB | LIBPATH | EXTERNAL_INCLUDE)
			echo "export $n=\"$v\"" >> $xout
		;;
		UCRT* | UNIVERSAL*)
			echo "export $n=\"$v\"" >> $xout
		;;
		WINDOWS*VERSION)
			v="`echo \"$v\" | sed 's/\/$//'`"
			echo "export $n=\"$v\"" >> $xout
		;;
		WINDOWS*)
			echo "export $n=\"$v\"" >> $xout
		;;
		*)
		;;
	esac

done < "$input"

rm -f /tmp/$base.* 2>/dev/null || true
